### ISSUE TITLE
ValueError: Scenario already Exist

### ISSUE THREAD

**Issue by cswh** [energiekollektiv/openmod.sh#19]
In dev branch on commit b49ef8a828e258e50476573d138395622220f817, with status_quo_explicit already being in the database, when trying to import status_quo_implict, the following error is raised:

```
builtins.ValueError
ValueError: Scenario already Exist

Traceback (most recent call last)
File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1994, in __call__
return self.wsgi_app(environ, start_response)
File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/clemens/znes_clemens/openmodsh/openmod.sh/openmod/sh/gui.py", line 66, in upload_file
raise ValueError('Scenario already Exist')
ValueError: Scenario already Exist
```

**Comment by simnh** [comment]
I fixed it for now on dev, but now uniqueness of scenario names is not checked anymore. I think I misunderstood the docs of sql-alchemy there...UniqueConstraint might probably not work as I thought it would..

**Comment by simnh** [comment]
I now used an other approach to check: 

http://stackoverflow.com/questions/5729500/how-does-sqlalchemy-handle-unique-constraint-in-table-definition

Please close if resolved...

**Comment by cswh** [comment]
it works.
