### ISSUE TITLE
sqlalchemy.orm.exc.DetachedInstanceError

### ISSUE THREAD

**Issue by cswh** [energiekollektiv/openmod.sh#34]
On 1f43e158f3f9aec4c9ad1286980cbd69dc0c4702 when clicking on `Production`-Tab on `edit_scenario`

```
Traceback (most recent call last):
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/clemens/znes_clemens/openmodsh/openmod.sh/openmod/sh/gui.py", line 270, in provide_results_api
    aggregated=True)
  File "/home/clemens/znes_clemens/openmodsh/openmod.sh/openmod/sh/api.py", line 589, in get_hub_results
    if r.successor.name == hub_name:
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 584, in get
    value = self.callable_(state, passive)
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/sqlalchemy/orm/strategies.py", line 530, in _load_for_state
    (orm_util.state_str(state), self.key)
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <ResultSequences at 0x7fde45cc4438> is not bound to a Session; lazy load operation of attribute 'successor' cannot proceed
```

**Comment by gnn** [comment]
Should be fixed now. Please test, while I don't have results in the db and close if the fix is correct.

**Comment by cswh** [comment]
works now
