### ISSUE TITLE
Bug db session

### ISSUE THREAD

**Issue by simnh** [energiekollektiv/openmod.sh#36]
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/attributes.py", line 584, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/strategies.py", line 530, in _load_for_state
    (orm_util.state_str(state), self.key)
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <ResultSequences at 0x7f5a8d0e3240> is not bound to a Session; lazy load operation of attribute 'successor' cannot proceed

**Comment by simnh** [comment]
```
for r in result_sequence_objects:
       print([i.name for i in r.predecessor.predecessors])
```

**Comment by gnn** [comment]
Ok. Auf welchem commit bist Du und was muss ich machen, um den Bug zu reproduzieren?

**Comment by gnn** [comment]
@simnh please check this and close it if it really no longer is an issue.

**Comment by cswh** [comment]
should be obsolete?
