### ISSUE TITLE
keyring is causing problems again -> we should not require oemof.db anymore

### ISSUE THREAD

**Issue by cswh** [energiekollektiv/openmod.sh#45]
```
Error initializing plugin Gnome = keyrings.alt.Gnome.
Traceback (most recent call last):
  File "/home/clemens/venvs/test/lib/python3.5/site-packages/keyring/backend.py", line 167, in _load_plugins
    init_func = ep.load()
  File "/home/clemens/venvs/test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/clemens/venvs/test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/clemens/venvs/test/lib/python3.5/site-packages/keyrings/alt/Gnome.py", line 11, in <module>
    from keyring.py27compat import unicode_str
ImportError: cannot import name 'unicode_str'

```

So far we only need oemof.db for the cfg which we could just implement ourselves and then reduce our requirements. Any objections?

**Comment by gnn** [comment]
I was with you initially, but unfortunately `oemof.db` is also used in `openmod.sh.api` for a little bit more than configuration which I don't want to duplicate (yet).
~~The good news: the exception actually does nothing. The code still runs normally (at least for me). It really is just an annoying message while developing that probably isn't even visible in normal deployment. I'd rather fix the error upstream in `oemof.db` hopefully even getting rid of the `keyrings.alt` requirement. That's an optional add on to `keyring` that users who need it (not us) can install.
I'm going to look into this. Am working on `oemof.db` a bit currently anyways.~~
Even better. Fixed by the `keyrings.alt` developer in 2.2.

**Comment by cswh** [comment]
> The good news: the exception actually does nothing.

Unfortunately it does something ;). When deploying on the server the exception did not allow to setup the databse with `setup-database.py`. So we should leave it for now with the oemof.db fork and have a look at the big picture in May.

**Comment by gnn** [comment]
> When deploying on the server the exception did not allow to setup the database with setup-database.py

Ah, (not so) nice one. But see my last sentence. Stuff works again. No exception anymore, with the current packages.
