### ISSUE TITLE
"Run simulation" doesn't queue jobs

### ISSUE THREAD

**Issue by simnh** [energiekollektiv/openmod.sh#64]

**Comment by simnh** [comment]
I guess this is the reason why? 

Traceback (most recent call last):
  File "/home/simon/uni/repos/openmod/openmod.sh/.venv/lib/python3.5/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/simon/uni/repos/openmod/openmod.sh/.venv/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/simon/uni/repos/openmod/openmod.sh/.venv/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/simon/uni/repos/openmod/openmod.sh/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/simon/uni/repos/openmod/openmod.sh/.venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/simon/uni/repos/openmod/openmod.sh/.venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/simon/uni/repos/openmod/openmod.sh/.venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/simon/uni/repos/openmod/openmod.sh/.venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/simon/uni/repos/openmod/openmod.sh/.venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/simon/uni/repos/openmod/openmod.sh/.venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/simon/uni/repos/openmod/openmod.sh/.venv/lib/python3.5/site-packages/flask_login/utils.py", line 225, in decorated_view
    return func(*args, **kwargs)
  File "/home/simon/uni/repos/openmod/openmod.sh/openmod/sh/gui.py", line 256, in run_simulation
    user = fl.current_user.name
  File "/home/simon/uni/repos/openmod/openmod.sh/.venv/lib/python3.5/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'name'

**Comment by simnh** [comment]
This error only comes when one is not logged in...@gnn will alter the error message. But jobs are listed now
